id: A90448603
title: Words Spoken at the Moment of Passing
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:49:20.801345
  last_modified_at: 2022-03-01 01:49:20.801352
